

# default_model: gpt-5-nano
# default_model: haiku
default_model: gpt-5-nano

logger:
    progress_display: false
    show_chat: true
    truncate_tools: false

mcp: 
    servers: 
        mcp_browser_use:
            command: "/Users/janspoerer/code/agents/mcp_browser_use/.venv/bin/python"
            args: ["-m", "mcp_browser_use"]
